# version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: mlflow_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local

# https://geshan.com.np/blog/2021/12/docker-postgres/
# docker run --name basic-postgres --rm \
#   -e POSTGRES_USER=postgres \
#   -e POSTGRES_PASSWORD=4y7sV96vA9wv46VR \
#   -e PGDATA=/var/lib/postgresql/data/pgdata \
#   -v /tmp:/var/lib/postgresql/data \
#   -p 5432:5432 \
#   -it postgres:14.1-alpine
